### 환경 변수 설정
@host = http://192.168.0.21:8080
@email = applewlghks321@gmail.com


### 1. 인증번호 전송 요청
# 이 요청을 실행(Run)하면 메일함으로 번호가 날아갑니다.
POST {{host}}/api/users/email/send
Content-Type: application/json

{
  "email": "{{email}}"
}


### 2. 인증번호 검증 요청
POST {{host}}/api/users/email/verify
Content-Type: application/json

{
  "email": "{{email}}",
  "authCode": "160035"
}